# You may add here your
# server {
#       ...
# }
# statements for each of your virtual hosts to this file

##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

server {
    if ($host = lk.billing.axiostv.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 192.168.19.5:80;
#       listen [::]:80 default_server ipv6only=on;
        access_log  off;
        error_log   off;
#        include letsencrypt;

        server_name lk.billing.axiostv.ru;

        location / {
                try_files $uri $uri/ =404;
                return 301 "https://lk.billing.axiostv.ru/";
        }


}


server {
    listen 192.168.19.5:443 default_server ssl;
    charset utf-8;
    autoindex off;
    server_name "lk.billing.axiostv.ru";
    root "/usr/axbills/cgi-bin";
    index index.cgi;

    ssl_certificate /etc/letsencrypt/live/lk.billing.axiostv.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lk.billing.axiostv.ru/privkey.pem; # managed by Certbot

    access_log /var/log/nginx/billing_access.log;
    error_log /var/log/nginx/billing_error.log;

	location / {
		root "/usr/axbills/cgi-bin/";
		index index.cgi;

	}

        location ~* \.php$ {
                fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
                fastcgi_index index.php;
                fastcgi_read_timeout 360;
		include fastcgi_params;
        }

	location ~* \.cgi|pm$ {
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
		fastcgi_index index.cgi;
		fastcgi_pass_header Authorization;
		fastcgi_param HTTP_CGI_AUTHORIZATION $http_authorization;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_read_timeout 360;
		include fastcgi_params;
	}

	location /styles/ {
		root /usr/axbills/cgi-bin/;
	}

	location /admin/ {
		alias "/usr/axbills/cgi-bin/admin/";
		index index.cgi;

	}

	location ^~ /api.cgi {
		try_files $uri /api.cgi$is_args$args;
		allow all;
		gzip off;
		fastcgi_param HTTPS on;
		fastcgi_pass unix:/var/run/fcgiwrap.socket;
 
		fastcgi_index index.cgi;
		fastcgi_param HTTP_CGI_AUTHORIZATION $http_authorization;
		fastcgi_param SCRIPT_FILENAME  /usr/axbills/cgi-bin$fastcgi_script_name;
		include fastcgi_params;
	}

        location ^~ /img/ {
                alias /usr/axbills/cgi-bin/img/;
                location ~* \.(ico|jpg|gif|png|css|js|JPG|GIF)$ {
        allow all;
        }
        deny all;
        }

	location ^~ /images/ {
		alias /usr/axbills/AXbills/templates/;
		location ~* \.(jpg|gif|png|css|js|JPG|GIF)$ {
        allow all;
      }
	deny all;
    }


}
