[219999] ; #Гамов Игорь Евгеньевич  
type=friend
;canreinvite=no
host=dynamic
username=219999
secret=321321321
dtmfmode=rfc2833
nat=yes
context=default

;callerid=\"\" <219999>
;allow=ulaw
;allow=alaw
