DROP TABLE IF EXISTS `MFISOFT_ABONENT`;
DROP TABLE IF EXISTS `MFISOFT_ABONENT_SERVICES`;
DROP TABLE IF EXISTS `MFISOFT_GATEWAYS`;
DROP TABLE IF EXISTS `MFISOFT_IP_PLAN`;
DROP TABLE IF EXISTS `MFISOFT_PAYMENT`;
DROP TABLE IF EXISTS `MFISOFT_PHONE_SPECIAL`;
DROP TABLE IF EXISTS `MFISOFT_SUPPLEMENTARY_SERVICES`;

CREATE TABLE IF NOT EXISTS `MFISOFT_ABONENT` (
  `ABONENT_ID` int(10) unsigned NOT NULL,
  `CONTRACT_DATE` date NOT NULL DEFAULT '1970-01-01',
  `CONTRACT` varchar(10) NOT NULL DEFAULT '',
  `ACCOUNT` varchar(10) NOT NULL,
  `ABONENT_TYPE` tinyint(2) NOT NULL DEFAULT '42',
  `UNSTRUCT_NAME` varchar(64) NOT NULL,
  `BIRTH_DATE` varchar(10) NOT NULL,
  `IDENT_CARD_TYPE_ID` int(2) DEFAULT '1',
  `IDENT_CARD_SERIAL` varchar(16) NOT NULL DEFAULT '',
  `IDENT_CARD_DESCRIPTION` varchar(300) NOT NULL DEFAULT '',
  `IDENT_CARD_UNSTRUCT` varchar(300) NOT NULL DEFAULT '',
  `NAME_INFO_TYPE` tinyint(1) NOT NULL DEFAULT '1',
  `IS_COMPANY` BOOL NOT NULL DEFAULT false,
  `BANK` varchar(512) NOT NULL DEFAULT '',
  `BANK_ACCOUNT` varchar(250) NOT NULL DEFAULT '',
  `FULL_NAME` varchar(128) NOT NULL DEFAULT '',
  `INN` varchar(64) NOT NULL DEFAULT '',
  `CONTACT` varchar(128) NOT NULL DEFAULT '',
  `PHONE_FAX` varchar(128) NOT NULL DEFAULT '',
  `STATUS` tinyint(1) NOT NULL DEFAULT '0',
  `ACTUAL_FROM` datetime DEFAULT '1970-01-01 00:00:01',
  `ACTUAL_TO` datetime DEFAULT '0000-00-00 00:00:00',
  `ATTACH` datetime DEFAULT '1970-01-01 00:00:01',
  `DETACH` datetime DEFAULT '0000-00-00 00:00:00',
  `ZIP` varchar(7) NOT NULL DEFAULT '',
  `COUNTRY` varchar(64) NOT NULL DEFAULT '',
  `REGION` varchar(48) NOT NULL DEFAULT '',
  `ZONE` varchar(48) NOT NULL DEFAULT '',
  `CITY` varchar(32) NOT NULL DEFAULT '',
  `STREET` varchar(100) NOT NULL DEFAULT '',
  `BUILDING` varchar(10) NOT NULL DEFAULT '',
  `APARTMENT` varchar(10) NOT NULL DEFAULT '',
  `REG_ZONE` varchar(48) NOT NULL DEFAULT '',
  `REG_CITY` varchar(32) NOT NULL DEFAULT '',
  `REG_STREET` varchar(100) NOT NULL DEFAULT '',
  `REG_BUILDING` varchar(10) NOT NULL DEFAULT '',
  `REG_APARTMENT` varchar(10) NOT NULL DEFAULT '',
  `ABONENT_ADDR_BEGIN_TIME` datetime DEFAULT '1970-01-01 00:00:01',
  `ABONENT_ADDR_END_TIME` datetime DEFAULT '0000-00-00 00:00:00',
  `PHONE` varchar(32) NOT NULL,
  `EQUIPMENT_TYPE` int(1) NOT NULL DEFAULT '0',
  `MAC` varchar(32) NOT NULL DEFAULT '',
  `LOGIN` varchar(30) NOT NULL,
  `E_MAIL` varchar(255) NOT NULL,
  `IP_TYPE` int(11) NOT NULL DEFAULT '0',
  `IPV4` int(10) unsigned NOT NULL DEFAULT '0',
  `IPV4_MASK` int(10) unsigned NOT NULL DEFAULT '4294967295',
  `ABONENT_IDENT_BEGIN_TIME` datetime DEFAULT '1970-01-01 00:00:01',
  `ABONENT_IDENT_END_TIME` datetime DEFAULT '0000-00-00 00:00:00',
  `TP_ID` int(10) NOT NULL COMMENT 'ID услуги',
  `ABONENT_SRV_BEGIN_TIME` datetime DEFAULT '1970-01-01 00:00:01',
  `ABONENT_SRV_END_TIME` datetime DEFAULT '0000-00-00 00:00:00',
  `PARAMETER` varchar(256) NOT NULL DEFAULT '',
  primary key `ABONENT_ID`(`ABONENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Структура таблицы `SORM_PAYMENT`
--

CREATE TABLE IF NOT EXISTS `MFISOFT_PAYMENT` (
  `PAYMENT_TYPE` int(2) NOT NULL DEFAULT '86',
  `PAY_TYPE_ID` int(4) NOT NULL,
  `PAYMENT_DATE` datetime NOT NULL,
  `AMOUNT` int(10) NOT NULL,
  `AMOUNT_CURRENCY` int(10) NOT NULL,
  `ABONENT_ID` int(10) NOT NULL COMMENT 'UID AXbills',
  `COUNTRY` varchar(20) DEFAULT NULL,
  `ZIP` int(6) NOT NULL,
  `REGION` varchar(20) DEFAULT NULL,
  `ZONE` varchar(20) DEFAULT NULL,
  `CITY` varchar(20) DEFAULT NULL,
  `STREET` varchar(20) DEFAULT NULL,
  `BUILDING` int(4) DEFAULT NULL,
  `APARTMENT` int(4) DEFAULT NULL,
  `axbills_id` int(11) NOT NULL,
  `PHONE` varchar(20) NOT NULL,
  `PAY_PARAMS` text NOT NULL,
  key `ABONENT_ID`(`ABONENT_ID`),
  key `axbills_id`(`axbills_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MFISOFT_GATEWAYS` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `IPV4` int(10) unsigned NOT NULL,
  `IPV6` varbinary(16) NOT NULL DEFAULT '',
  `GATE_TYPE` int(2) unsigned NOT NULL DEFAULT '0',
  `BEGIN_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(128) NOT NULL,
  `ZIP` int(10) NOT NULL DEFAULT '0',
  `COUNTRY` text,
  `CITY` varchar(48) NOT NULL DEFAULT '',
  `STREET` varchar(64) NOT NULL DEFAULT '',
  `BUILDING` varchar(10) NOT NULL,
  `BUILD_SECT` varchar(10) NOT NULL,
  `APARTMENT` varchar(10) NOT NULL,
  `last_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
     primary key `id`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MFISOFT_PHONE_SPECIAL` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PHONE_NUMBER` text,
  `DESCRIPTION` varchar(32) NOT NULL DEFAULT '',
  `BEGIN_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IPV4` int(10) unsigned NOT NULL,
  `IPV6` varbinary(16) NOT NULL DEFAULT '',
  `DELETED` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MFISOFT_IP_PLAN` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(32) NOT NULL DEFAULT '',
  `IPV4` int(10) unsigned NOT NULL,
  `IPV6` varbinary(16) NOT NULL DEFAULT '',
  `IPV4_MASK` int(2) unsigned NOT NULL,
  `IPV6_MASK` int(3) unsigned NOT NULL,
  `BEGIN_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED` int(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MFISOFT_ABONENT_SERVICES` (
  `ABONENT_ID` int(10) unsigned NOT NULL,
  `ID` int(4) unsigned NOT NULL,
  `MODULE` varchar(16) NOT NULL,
  `BEGIN_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `SERV_ID` (`ABONENT_ID`,`ID`,`MODULE`),
  KEY `ABONENT_ID` (`ABONENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MFISOFT_SUPPLEMENTARY_SERVICES` (
  `ID` int(2) unsigned NOT NULL,
  `MODULE` varchar(16) NOT NULL,
  `MNEMONIC` varchar(32) NOT NULL DEFAULT '',
  `BEGIN_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(100) NOT NULL DEFAULT '',
  `DELETED` int(1) unsigned NOT NULL DEFAULT '0',
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
