SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

ALTER TABLE iptv_services ADD COLUMN provider_id TINYINT DEFAULT NULL;
ALTER TABLE iptv_main ADD COLUMN subchannel_id varchar(32) NOT NULL DEFAULT '';