ALTER TABLE trafic_tarifs MODIFY COLUMN burst_limit_dl INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE trafic_tarifs MODIFY COLUMN burst_limit_ul INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE trafic_tarifs MODIFY COLUMN burst_threshold_dl INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE trafic_tarifs MODIFY COLUMN burst_threshold_ul INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE trafic_tarifs MODIFY COLUMN burst_time_dl INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE trafic_tarifs MODIFY COLUMN burst_time_ul INT(10) UNSIGNED NOT NULL DEFAULT '0';

