ALTER TABLE users_pi CHANGE contract_date contract_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE companies CHANGE contract_date contract_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

